encryptionsalt: v1:1rV3/5X7HUE=:v1:2YDBbOMuZwVLxzTU:hXcJZYTcteGG+GZr3XnG++Po8Bx6XQ==
config:
  infrastructure:KUBE-PROMETHEUS-STACK_VERSION: 66.2.2
  infrastructure:KUBEVIRT_VERSION: v1.3.1
  infrastructure:NGINX_NAMESPACE: ingress-nginx
  infrastructure:NGINX_VERSION: 4.11.3
  infrastructure:PROVISIONER_PATH: /tmp/local-path-provisioner
  infrastructure:PROVISIONER_VOLUME_TYPE: hostPath
  infrastructure:RECLAIM_POLICY: retain
  infrastructure:VOLUME_BINDING_MODE: Immediate
