version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directories: 
      - "/src"
      - "/src/application/welcome/neumorphism"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directories: 
      - "/src/application/ctfd"
      - "/src/application/ctfd/oidc"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directories: 
      - "/src/application/bastion"
      - "/src/application/ctfd"
      - "/src/application/nginx"
      - "/src/application/welcome"
      - "/src/application/challenges/backend"
    schedule:
      interval: "weekly"