version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/src"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/src/application/ctfd"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/src/application/ctfd/oidc"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/src/application/bastion"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/src/application/ctfd"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/src/application/nginx"
    schedule:
      interval: "daily"
