version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/src"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directories: 
      - "/src/application/ctfd"
      - "/src/application/ctfd/oidc"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directories: 
      - "/src/application/bastion"
      - "/src/application/ctfd"
      - "/src/application/nginx"
    schedule:
      interval: "weekly"