theme: jekyll-theme-slate
title: CTF Platform
description: >
  Microservice architecture using Pulumi, Kubernetes, and KubeVirt, monitoring with Prometheus and Grafana, zero-trust with Smallstep, SSO with Keycloak and much more!
show_downloads: true