theme: jekyll-theme-slate
title: CTF Platform
description: >
  Capture The Flag (CTF) platform development focussing on accessibility by deploying on cloud infrastructure, leveraging modern DevOps tools for infrastructure, ensuring strong security through containerization and VMs, and optimizing resource utilization to minimize the server footprint.
show_downloads: true