theme: jekyll-theme-slate
title: CTF Platform
description: >
  Development and optimization using technologies like Pulumi, Kubernetes, and KubeVirt. Monitoring with Prometheus and Grafana, implementing zero-trust with Smallstep, and SSO with Keycloak and much more.
show_downloads: true