name: Run Ansible Playbook

on:
  workflow_dispatch:
    inputs:
      CONTROL_HOST_IP:
        description: 'IP address of the control host'
        required: true
      WORKER_0_IP:
        description: 'IP address of worker 0'
        required: true
      WORKER_1_IP:
        description: 'IP address of worker 1'
        required: true
      LOGIN_SERVER_ADDRESS:
        description: 'HTTP address of login server'
        required: true
        default: http://34.88.225.69:8080

jobs:
  ucloud:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Add SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          echo "${{ vars.SSH_PUBLIC_KEY }}" > ~/.ssh/id_ed25519.pub
          chmod 600 ~/.ssh/id_ed25519
          chmod 644 ~/.ssh/id_ed25519.pub
        
      - name: Create hosts-ucloud.ini
        env:
            CONTROL_HOST_IP: ${{ github.event.inputs.CONTROL_HOST_IP }}
            WORKER_0_IP: ${{ github.event.inputs.WORKER_0_IP }}
            WORKER_1_IP: ${{ github.event.inputs.WORKER_1_IP }}
            LOGIN_SERVER: ${{ github.event.inputs.LOGIN_SERVER_ADDRESS }}
        run: |
            cat hosts.ini.example | envsubst > hosts.ini
        working-directory: ucloud-k8s/ansible

      - name: Create tailscale_key
        run: |
          echo ${{ secrets.TAILSCALE_KEY }} > tailscale_key
        working-directory: ucloud-k8s

      - name: Create pulumi_passphrase
        run: |
          echo ${{ secrets.PULUMI_PASSPHRASE }} > pulumi_passphrase
        working-directory: ucloud-k8s

      - name: Run Ansible Playbook
        run: |
          ansible-playbook cluster.yml
        working-directory: ucloud-k8s/ansible
