name: Run Ansible Playbook

on:
  workflow_dispatch:
    inputs:
      CONTROL_HOST_IP:
        description: 'IP address of the control host'
        required: true
      WORKER_0_IP:
        description: 'IP address of worker 0'
        required: true
      WORKER_1_IP:
        description: 'IP address of worker 1'
        required: true

jobs:
  ucloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Add SSH keys
        run: |
          mkdir -p ~/.ssh
          echo ${{ secrets.SSH_PRIVATE_KEY }} > id_ed25519
          echo ${{ vars.SSH_PUBLIC_KEY }} > id_ed25519.pub
          chmod 600 ucloud
          chmod 644 ucloud.pub
        working-directory: ~/.ssh

      - name: Create hosts-ucloud.ini
        env:
            CONTROL_HOST_IP: ${{ github.event.inputs.CONTROL_HOST_IP }}
            WORKER_0_IP: ${{ github.event.inputs.WORKER_0_IP }}
            WORKER_1_IP: ${{ github.event.inputs.WORKER_1_IP }}
        run: |
            cat hosts.ini.example | envsubst > hosts.ini
        working-directory: ${{ github.workspace }}/ucloud-k8s/ansible

      - name: Create tailscale_key
        run: |
          echo ${{ secrets.TAILSCALE_KEY }} > tailscale_key
        working-directory: ${{ github.workspace }}/ucloud-k8s/ansible

      - name: Run Ansible Playbook
        run: |
          ansible-playbook cluster.yml
        working-directory: ${{ github.workspace }}/ucloud-k8s/ansible
